### ISSUE TITLE
Effluent Turbidity vs. PACl Dosage Exp: 1.1mg/L, 0.65mg/L, 0.2mg/L - LOWER PACL STOCK CONCENTRATION

### ISSUE THREAD

**Issue by dylanvucornell** [AguaClara/stars_filter_theory#18]
1.1mg/L PACl:
Effluent turbidity deviates from influent turbidity. Effluent NTU is consistently less than influent NTU.
![image](https://user-images.githubusercontent.com/35712770/37669758-048746f2-2c3e-11e8-861f-8c9c7fc0a179.png)

0.65mg/L PACl:
Effluent turbidity deviates from influent turbidity. Effluent NTU is consistently less than influent NTU.
![image](https://user-images.githubusercontent.com/35712770/37670905-d81e2c36-2c40-11e8-84d2-42b619eb23f4.png)

0.2mg/L PACl:
Effluent turbidity deviates from influent turbidity. Effluent NTU is consistently less than influent NTU.
![image](https://user-images.githubusercontent.com/35712770/37672287-094a401c-2c44-11e8-833f-df934f667367.png)

**Comment by dylanvucornell** [comment]
@lucindali @WPennock @monroews

**Comment by monroews** [comment]
Please add a description of the experiment and an explanation for the question. We would expect effluent turbidity to be lower than influent turbidity and so it isn't clear what the question is.

**Comment by AlisonAndrea17** [comment]
We wanted to analyze the effect of PACL on effluent turbidity. We know for a fact that PACL changes flocs particles size. The results show that effluent turbidity decreases when adding PACL. This trend can be seen clearly when comparing our control experiment to 1.1mg/L. However, within the range of PACL dosages used we see that effluent turbidity doesn’t fluctuate significantly, which led us to think that the range of PACL used doesn’t affect the size of the flocs considerably as for us to see large fluctuations on the effluent turbidity of the experiments conducted. 

To be more specific, we wanted to let you know about our results and hear your opinion on the trend we found and how this could affect filter performance.

Lastly, we've hypothesize that since PACL isn't changing particles size significantly, then the strength between the particles due to PACL is the main factor affecting filter performance.

**Comment by monroews** [comment]
Mean floc size or the 90th percentile floc size might not be correlated with filter performance because filter performance is about the small flocs and primary particles, not the big flocs.
Thus you can't use effluent turbidity as a way to estimate floc size.
You have strong evidence that PACl does change floc size and that evidence should not be ignored. Filter run times decrease as PACl dose increases.
