### ISSUE TITLE
Hypotheses for the maximum particle load for a filter

### ISSUE THREAD

**Issue by monroews** [AguaClara/stars_filter_theory#2]
> We're currently wrapping up our literature review on researching possible failure mechanisms that should stay constant from trial to trial. This was done because we had found last semester that the filter had different mass accumulated before failure; thus, ruling out the theory that the filter has a mass capacity before failure.
> 
> We currently have some different theories for filter failure mechanism and tentative procedures, and we would like to meet with you to run through them and get your input on the whole situation. When would be good time for us to talk?

I don't think we ever had a hypothesis that failure was related to mass. Our expectation was that filter constrictions had a maximum volume.
The HRS team learned that coagulant nanoparticles attach to the flocculator walls and there is strong evidence that the fraction of the coagulant that is lost to the flocculator walls increases with time. It was necessary to "pig" or high pressure wash the flocculator to remove coagulant deposition. Would this effect be consistent with your observations?

What are your proposed filter failure mechanisms?

**Comment by ecantlebary** [comment]
The increase of coagulant is not consistent with out results. We saw a faster failure time with a high PACl dosage. The accumulation of coagulant on the flocculator is not significant to justify the large range of failure times (~2 hours to ~9 hours). Unless there is a very large variation in the amount of accumulation based on the dosage of PACl (much higher rate of accumulation for a higher PACl dosage), it isn't logical that it would change the filter time by so much. 

Furthermore, even if there was a large correlation between rate of accumulation and the PACl dosage, it does not explain why the filter fails in a shorter time period for a large PACl dosage. If there was a fraction of the PACl attaching to the flocculator tubing, the total dosage of PACl would still be higher for the 2mg/L experiments than the 0.1mg/L experiments. Given that we keep the influent turbidity and flow rate the same, the PACl dosage should be the only factor affecting failure time, and the hypothesis that the variation in filter failure time is caused by accumulation of flocs contradicts our data.

**Comment by AlisonAndrea17** [comment]
Possible filter failure mechanisms:

1. Porosity: Filter fails with a specific reduction in the porosity of the filter bed. This mechanism can be studied by comparing the volume of average flocs vs. the volume of the pores. We could get the volume of flocs by looking at dosage of coagulant vs. floc size as it has been referenced in literature. This volume-dependence relation could explain why higher coagulant dosage cause faster failure time.

We could test porosity through finding water displacement on a clean, dry bed before experimentation, and then find water displacement on a dirty, dry bed after the filter goes to failure. The difference in the total volume of water absorbed would be equivalent to the total change in void space in the filter. From this, porosity both before and after the experiment can be measured. 

2. Redeposition of aggregates in different parts of the filter bed: When large particles (aggregates) deposit onto smaller ones in the filter bed, there’s the possibility that the flocs will resuspend and make it out of the filter. Additionally, particles may deposit in places other than the pores. Eventually, the buildup of aggregates would cause the filter to fail.

3. Clogging near the influent pipe due to particle deposition blocks the sand filter capillaries, which decreases the capacity of the sand filter to clean the water and causes variability in the filter failure time.

**Comment by monroews** [comment]
@lucindali can provide insight into how increasing the coagulant dose would increase the fraction of the clay surfaces that are coated with coagulant nanoparticles, how the bond between two clay particles can thus be stronger, how this can lead to larger flocs, and how the fractal nature of flocs reveals that larger flocs are less dense. How might this understanding of fractal flocs connect to your observations from last semester?
![image](https://user-images.githubusercontent.com/28540907/36160033-33da39a6-10ae-11e8-9f7a-73abe9afb426.png)

In my earlier post I suggest that there might be a limiting volume of constrictions that can build up in the filter and once that volume is reached that break through will begin. If that hypothesis is true, what does this mean about floc size?

By the way, these results are very impressive and need to be published!

**Comment by dylanvucornell** [comment]
In response to your first question and floc density assumptions, we should expect that the higher the coagulant dosage, the larger the flocs. This would lead to the hypothesis that because the flocs have a larger volume relative to the average pore size in the sand bed, the flocs should clog the pores faster, as it should take less particles to reach that deposition volume limit. Thus, as this continues to happen throughout the sand bed, the filter should fail when pores clog. Sensibly, the theory is that the filter fails when all capillaries are clogged or "blocked" in some way. However, in the many of the papers that we read through, it was concluded that not all the capillaries needed to be clogged before the filter fails. We are not sure why this is the case.

In response to your second question, we hypothesize that the higher the PACl dosage, the larger the size of the clay flocs deposited. As such, the shear force on the deposited flocs should be greater, as the surface area of the particle exposed to the water flow is greater. Thus, this increased shear force would break these flocs off of the media particle and exit the filter. This would lead to a shorter failure time as more flocs break off and exit in the effluent water. Whereas, we think that in the case of lower PACl dosages, and smaller flocs, the "building up" of deposition in the constriction would be better facilitated because shear force on the individual particle would be less (with decreased surface area), allowing for more of the smaller flocs to deposit beside the already deposited flocs (in the "donut" geometry previously predicted). The "build up" time in the deposition of smaller flocs could be the reason why we see that the lower coagulant dosage correlates to a longer failure time. Furher, this difference in how different size flocs deposit, re-entrain, and exit the filter could explain why we noticed very little change in effluent turbidity based on varying coagulant dosages until failure time in our last semester's work.

We will talk more with Lucinda tomorrow about this, but we would love some more input so we have even more to think about and discuss. Thanks!
