### ISSUE TITLE
Experimentation with 0.02 to 0.1 mg/L PACl dose

### ISSUE THREAD

**Issue by ecantlebary** [AguaClara/stars_filter_theory#23]
The current values of PACl dosage that our team uses are, in general, a lot higher than existing AguaClara plants and other apparatuses. We will be redoing experiments with lower PACl doses. 

For all of these experiments, the flow rate will be 1.967 mL/s, which is the same as all other experiments we run. The influent turbidity will be 5 NTU, and the run time will be 12 hours unless the team decides it should be adjusted after observing failure times. 

2 sets of experiments will be run. 

The first set will be run with PACl doses of 0.02, 0.04, 0.06, 0.08, and 0.1 mg/L of PACl on our apparatus under the given parameters.  The second set will be run with the same doses, but a needle constriction will be used to break the particles up. 

The purpose of these experiments is to observe the effects of flocculation on filter failure times with a more realistic PACl dose. This means that the size of flocs going through the filter without the constriction are more likley to be representative of AguaClara filtration, and there will likely be a more uniform distribution of theses flocs. Further, from observations of previous data, lower PACl dosages have produced better filter performance - with longer failure times at no cost of higher average effluent turbidity. Thus, we want to be investigating filter performance at these lower PACl dosages.

Results will be posted in the comments below per PACl dosage.

**Comment by dylanvucornell** [comment]
[Low Concentration PACl Pump RPM and Stock Conc..xlsx](https://github.com/AguaClara/stars_filter_theory/files/1895741/Low.Concentration.PACl.Pump.RPM.and.Stock.Conc.xlsx)


New PACl pump RPM values to run and the new stock concentration.

**Comment by dylanvucornell** [comment]
**0.1 mg/L - 12h run.**
![image](https://user-images.githubusercontent.com/35712770/38756392-644c5e04-3f37-11e8-8f34-5e555977e1ec.png)
[22-04-18 0.1 mgL.xlsx](https://github.com/AguaClara/stars_filter_theory/files/1908818/22-04-18.0.1.mgL.xlsx)

Effluent turbidity stayed around 0.1-0.15 NTU throughout the 12h experiment. There didn't seem to be a dramatic divergence in effluent turbidity in this test period, which would suggest that the filter stayed operational during this whole run. This followed our previously seen trend of an exponential increase in failure time with decreasing PACl dosages in the range of dosages we've tested. We will follow up this experiment with a 24h run time with the same parameters in order to try to find the typical divergence in effluent turbidity/filter failure time.

**Comment by dylanvucornell** [comment]
**0.04 mg/L - 12h run.**

![image](https://user-images.githubusercontent.com/35712770/39156848-017d0282-4726-11e8-94fc-0e1a470e8202.png)

[20-04-18 0.04 mgL without constriction.xlsx](https://github.com/AguaClara/stars_filter_theory/files/1940263/20-04-18.0.04.mgL.without.constriction.xlsx)

It looks like the performance for the 0.04 mg/L PACl experiment was worse than the 0.1 mg/L PACl experiment in all causes. The filter failed around 3.6h. The effluent turbidity stayed around 0.3 NTU instead of the 0.1 NTU found in the previous experiment. However, instead of the sharp divergence seen in effluent turbidity seen in higher PACl dosage experiments, the divergence was very slow - this seems to suggest that the filter slowly failed rather than "hitting a capacity" and instantly failing. The team is looking to explore PACl dosage ranges between 0.04-0.10 mg/L now to try to see a trend.

**Comment by dylanvucornell** [comment]
**0.08 mg/L - 12h run.**

![image](https://user-images.githubusercontent.com/35712770/39275172-4d7eec12-48b2-11e8-9b39-881b8faf97e8.png)

[24-04-18 0.08 mgL without constriction.xlsx](https://github.com/AguaClara/stars_filter_theory/files/1948972/24-04-18.0.08.mgL.without.constriction.xlsx)

It looks like the performance for the 0.08 mg/L PACl experiment was worse than the 0.1 mg/L PACl experiment, and similar to the 0.04 mg/L PACL experiment, in all cases. The filter failed around 3.8h. The effluent turbidity stayed around 0.3 NTU. This leads us to think that something was wrong with 0.10 mg/L PACl experiment we ran. We will look to rerun that experiment.

**Comment by dylanvucornell** [comment]
**0.1 mg/L rerun - 12h run.**

![image](https://user-images.githubusercontent.com/35712770/39547655-3ac400a2-4e26-11e8-8217-0d4be643b422.png)

[01-05-18 0.1 mgL rerun.xlsx](https://github.com/AguaClara/stars_filter_theory/files/1968811/01-05-18.0.1.mgL.rerun.xlsx)

This is inconsistent with the first 0.1 mg/L test that we performed. We have run this test multiple times but the results we previously found have no been repeated since. The lowest the NTU drops in this test was around 0.3NTU and it fails around 1.4h.
